services:
  app:
    image: saperspecnaz/node-ci-app:latest
    ports:
      - "3000:3000"

  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.53
    command: --interval 30 --debug

